class LocatorsBuyingflow:
    MainPageBlackTopsProduct1AddtoCartButton = '//*[@id="tyche_products-1"]/div/div[2]/div/div[1]/div/div[1]/div/div/div[2]/a'
    MainPageBlackTopsProduct2AddtoCartButton = '//*[@id="tyche_products-1"]/div/div[2]/div/div[1]/div/div[2]/div/div/div[2]/a'
    MainPageMyCartButton = '//*[@id="page"]/header[1]/div/div/div/ul/li[2]/a'
    MainPageMyAccountButton = '//*[@id="page"]/header[1]/div/div/div/ul/li[3]/a'
    MainPageMostwantedCattegorybutton = '//*[@id="menu-item-128"]/a'
    MainPageCategoriesCategorylist = '//*[@id="menu-item-123"]/a'
    MainPageCategoriesCategorylistShoes ='//a[@title="Shoes"]'
    ShoesCattegoryProduct1AddtocartButton = '//*[@id="page"]/div/div/div[2]/div/ul/li[1]/a'
    MainpageTrendsCategory1ProductAddtocart = '//*[@id="tyche_products-7"]/div/div[2]/div/div[1]/div/div[1]/div/div/div[2]/a'
    MainpageTrendsCategory2ProductAddtocart = '//*[@id="tyche_products-7"]/div/div[2]/div/div[1]/div/div[2]/div/div/div[2]/a'
    MainpageTrendsCategory3ProductAddtocart = '//*[@id="tyche_products-7"]/div/div[2]/div/div[1]/div/div[3]/div/div/div[2]/a'
    MainpageTrendsCategory4ProductAddtocart = '//*[@id="tyche_products-7"]/div/div[2]/div/div[1]/div/div[4]/div/div/div[2]/a'

    MostwantedCategory1Product1Photo = '//*[@id="page"]/div/div/div[2]/div/ul/li[1]/a[1]/img'
    ProductPageReviewButton ='//*[@id="tab-title-reviews"]/a'
    ProductPageDescriptionButton = '//*[@id="tab-title-description"]/a'
    ProductPageAddtocartButton = '//*[@id="product-31"]/div[2]/form/button'




    MainPageGenericShopbutton = '//*[@id="masthead"]/div/div/div/div/a'
    BracketProduct1Quantityplusbutton = '//*[@id="post-6"]/div[2]/form/table/tbody/tr[1]/td[5]/div/div/a[2]/span'
    BracketProduct2Quantityplusbutton = '//*[@id="post-6"]/div[2]/form/table/tbody/tr[2]/td[5]/div/div/a[2]/span'
    BracketProduct1Quantityminusbutton = '//*[@id="post-6"]/div[2]/form/table/tbody/tr[1]/td[5]/div/div/a[1]/span'
    BracketProduct2Quantityminusbutton  ='//*[@id="post-6"]/div[2]/form/table/tbody/tr[2]/td[5]/div/div/a[1]/span'
    BracketUpdatecartbutton = 'update_cart'
    BracketReturnToShopButton = '//*[@id="post-6"]/div[2]/p[2]/a'
    BracketProduct2DeleteButton = '/html/body/div[1]/div/div[2]/div/div/main/article/div[2]/form/table/tbody/tr[2]/td[1]/a'
    BracketProduct4DeleteButton ='//*[@id="post-6"]/div[2]/form/table/tbody/tr[4]/td[1]/a'
    BracketProduct6DeleteButton ='//*[@id="post-6"]/div[2]/form/table/tbody/tr[6]/td[1]/a'
    BracketCouponInput = '//*[@id="coupon_code"]'
    BracketProceedtoCheckoutButton = '//*[@id="post-6"]/div[2]/div/div/div/a'
    BracketFirstnameinput = '//*[@id="billing_first_name"]'
    BracketLastnameInput = '//*[@id="billing_last_name"]'
    BracketCompanyInput = '//*[@id="billing_company"]'
    BracketCountryListbutton = '//*[@id="select2-billing_country-container"]'
    BracketCountryListSearchbar = '/html/body/span/span/span[1]/input'
    BracketStreetaddressInput = '//*[@id="billing_address_1"]'
    BracketStreetAddressOptionalInput = '//*[@id="billing_address_2"]'
    BracketZipCodeInput = '//*[@id="billing_postcode"]'
    BracketTownInput = '//*[@id="billing_city"]'
    BracketStateListbutton = '//*[@id="billing_state_field"]/span/span[1]/span'
    BracketStateListSearchBar ='/html/body/span/span/span[1]/input'
    BracketPhoneInput = '//*[@id="billing_phone"]'
    BracketEmailInput = '//*[@id="billing_email"]'
    BracketCreateAnAccountcheckbox = '//*[@id="createaccount"]'
    BracketCreateAnAccountPasswordInput = '//*[@id="account_password"]'
    BracketShippingtoaDiffrentadresCheckbox  = '//*[@id="ship-to-different-address-checkbox"]'
    BracketDiffrentAddressFistNameInput = '//*[@id="shipping_first_name"]'
    BracketDiffrentAddressLastNameInput = '//*[@id="shipping_first_name"]'
    BracketDiffrentCompanyNameinput = '//*[@id="shipping_company"]'
    BracketDiffrentCountryListbutton = '//*[@id="select2-shipping_country-container"]'
    BracketDiffrentCountryListSearchbar = '/html/body/span/span/span[1]/input'
    BracketDiffrentStreetAddres ='//*[@id="shipping_address_1"]'
    BracketDiffrentStreetAddress2 = '//*[@id="shipping_address_2"]'
    BracketDiffrentTownInput = '//*[@id="shipping_city"]'
    BracketDiffrentStateButton = '//*[@id="shipping_state_field"]/span/span[1]/span'
    BracketDiffrentStateSearchBar = '/html/body/span/span/span[1]/input'
    BracketDiffrentPostCodeinput = '//*[@id="shipping_postcode"]'
    BracketDiffrentOrderNotes = '//*[@id="order_comments"]'


    BracketDirectbanktransferCheckbox = '//*[@id="payment_method_bacs"]'

    BracketCheckPaymentsCheckbox = '//*[@id="payment_method_cheque"]'
    BracketCashOnDeliveryCheckbox = '//*[@id="payment_method_cod"]'
    BracketPaypalCheckbox = '//*[@id="payment_method_paypal"]'
    BracketPlaceOrderButton = '//*[@id="place_order"]'
    BracketOrderNotesInput = '//*[@id="order_comments"]'

    BracketThankyoutext = '//*[@id="post-7"]//*[contains(@class, "woocommerce-notice woocommerce-notice--success woocommerce-thankyou-order-received") and contains(text(), "Thank you. Your order has been received.")]'
    BracketPrintButton = '//*[@id="post-7"]/div[2]/div/section[2]/h3/a'



